# Generated by Django 4.0.4 on 2022-04-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0002_userfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
    ]
