# Generated by Django 4.0.4 on 2022-04-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0003_alter_userfiles_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiles',
            name='desc',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
