# Generated by Django 4.0.4 on 2022-04-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0005_userfiles_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
